### ISSUE TITLE
Can't access `/sitemap.xml` after install

### ISSUE THREAD

**Issue by mijustin** [alt-design/Alt-Sitemap-Addon#1]
I installed the add-on, configured the collections, and visited `justin4.test/sitemap.xml` locally, but I get these errors:

https://flareapp.io/share/v5pKppx7

**Comment by AltRob** [comment]
Hi Justin, 
Thanks for raising. Can I see a screenshot from your admin page cp/alt-design/alt-sitemap ?
Many thanks,
Rob

**Comment by mijustin** [comment]
I needed a solution quick, so I had to uninstall Alt-Sitemap and go with a different solution.
