### ISSUE TITLE
Google Search Console: "Your Sitemap appears to be an HTML page"

### ISSUE THREAD

**Issue by tobiv** [alt-design/Alt-Sitemap-Addon#2]
When I submit the sitemap url (https://site.com/sitemap.xml), Search Console complains that it is in HTML format. Judging from the source, it cleary is XML and also the HTTP headers say type XML. Can anybody reproduce this?

**Comment by Alt-Ben** [comment]
Hey @tobiv - should be fixed in the latest release!
