### ISSUE TITLE
Sitemap.xml requires admin access

### ISSUE THREAD

**Issue by senyil** [alt-design/Alt-Sitemap-Addon#3]
Hey thanks for the addon, it's amazing. For some reason my sitemap.xml not visible without admin login, do i need to edit anything?

**Comment by Alt-Ben** [comment]
Hey!

Thanks for the feedback 🙌 

This should be resolved in the latest version, if you update then it should work as expected.

Let me know if not!

**Comment by senyil** [comment]
Thanks, looks like I'm on 1.0.1 Released on 2023-11-13 with no updates

**Comment by Alt-Ben** [comment]
Hmm that's weird, Statamic hasn't flagged it as due for update, but if you run `composer update` it should bump it to v1.0.2

**Comment by senyil** [comment]
My bad! even it does look up to date on CP it wasn't when i check on composer.

**Comment by Alt-Ben** [comment]
It was the same for me to be fair! Glad it's working now!
